### ISSUE TITLE
[BUG] 11-blue-green.md file does not exsist

### ISSUE THREAD

**Issue by mifurm** [Azure/AKS-Landing-Zone-Accelerator#118]
**Describe the bug**
In the last statement of this article (https://github.com/Azure/AKS-Landing-Zone-Accelerator/tree/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform#getting-started) you refer to 11-blue-green.md file which does not exsists. https://github.com/Azure/AKS-Landing-Zone-Accelerator/blob/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/11-blue-green.md

**To Reproduce**
1. Go to web page: https://github.com/Azure/AKS-Landing-Zone-Accelerator/tree/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform#getting-started
2. Go down to section https://github.com/Azure/AKS-Landing-Zone-Accelerator/tree/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform#deploying-blue-green-aks-clusters
3. Look for sentence: "The details about the blue green deployment are documented [here](https://github.com/Azure/AKS-Landing-Zone-Accelerator/blob/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/11-blue-green.md)"
4. Click in the provided link to 11-blue-green.md file.
5. You will see the file does not exist. 

**Expected behavior**
The file should exist in the GitHub repo.

**Comment by mosabami** [comment]
#145 closes this
