### ISSUE TITLE
Create the self-signed certificate using Lets Encrypt [BUG]

### ISSUE THREAD

**Issue by bspann** [Azure/AKS-Landing-Zone-Accelerator#24]
**Describe the bug**
The Scenario for AKS-Secure-Baseline-PrivateCluster/Bicep/07-workload.md page talks about deploying the Ingress with HTTPS support. When you run the following command:

az aks command invoke --resource-group $ClusterRGName --name $ClusterName   --command "kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.yaml" 

you get a message back stating:

command started at 2022-07-01 20:25:59+00:00, finished at 2022-07-01 20:26:03+00:00 with exitcode=1
Unable to connect to the server: EOF

The cert-manager is not installed into the cluster.

**To Reproduce**
1. Connect to a private AKS cluster.
2. Issue the above command (az aks command invoke --resource-group $ClusterRGName --name $ClusterName   --command "kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.yaml")
3. Wait until the command comes back to the jumpbox (Bastion)
4. See error.

**Expected behavior**
cert-manager is installed into the cluster.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Terminal with Azure CLI

**Comment by mosabami** [comment]
hey @bspann  thanks for your feedback. this issue has now been resolved with #23 . Let me know if you still run into issues.

**Comment by mosabami** [comment]
closing the issue now @bspann
