### ISSUE TITLE
[FEATURE] - Blue Green Deployment Reference Implementation

### ISSUE THREAD

**Issue by vimorra** [Azure/AKS-Landing-Zone-Accelerator#26]
Add a reference implementation for the blue green pattern, usually adopted to control the deployment of new cluster versions.

I would like to have a reference implementation integrated in the AKS Secure Baseline. The implementation is based on Terraform and is retro.compatible with the previous, enabling deployment also of a single cluster.

**Comment by sebader** [comment]
The Azure Mission-Critical Reference Implementation does a full working version of blue-green deployments, including the pipeline automation (which is the actual tricky part in this): https://github.com/Azure/Mission-Critical-Online

**Comment by vimorra** [comment]
the idea is to provide blue green as generic pattern, that of course is also part of the mission critical workloads. Some users can be still interested in the blue green without implement a full mission critical architecture.

**Comment by sebader** [comment]
Indeed, and I don't mean that everybody needs to implement a full mission-critical architecture. People can also just take certain pieces of the reference implementation, like the blue-green deployment approach (and lots of them are).
I just wanted to give you a pointer to there, so you don't go and reinvent the wheel ;)
