### ISSUE TITLE
[FEATURE] Simplify the instructions for the Workload deployment

### ISSUE THREAD

**Issue by bahramr** [Azure/AKS-Landing-Zone-Accelerator#33]
The [steps](https://github.com/Azure/AKS-Landing-Zone-Accelerator/blob/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Terraform/08-workload.md) for the workload deployment are too complex and do not provide much instructional value.
Consider implementing the following enhancements:

1. Remove the steps to setup firewalls rule for the jumpbox
2. Connecting the ACR and AKV to the hub should have been done previously through the IaC bicep or terraform code
3. We should talk about the "AKS run command" as an alternative to running the kubectl commands from the jumpbox. All the commands should be changed to be run locally from the Linux jumpbox as that offers a better experience for the end user (also making use of the jumpbox and Bastionhost deployed in the environment).
4. Remove all the manual customizations that need to be done to the app yaml files. Instead use helm and pass the environment specific variables as parameters
5. Remove the steps to deploy ingress without HTTPS

**Comment by ahems** [comment]
The workload deployment can now be done via a GitHub action instead, which is much easier: [Steps](https://github.com/Azure/AKS-Landing-Zone-Accelerator/blob/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Bicep/02a-DeployUsingGitHubActions.md)

**Comment by mosabami** [comment]
we now have our all-in-one deployment option. GitHub action option needs to be updated https://github.com/Azure/AKS-Landing-Zone-Accelerator/tree/main/Scenarios/AKS-Secure-Baseline-PrivateCluster/Bicep/All-in-One-Bicep
