### ISSUE TITLE
Use -input=false in terraform github workflows / missing `location` input

### ISSUE THREAD

**Issue by defenestration** [Azure/AKS-Landing-Zone-Accelerator#7]
the deployInfrastructure.yml seems to be missing this flag and Scenarios/Secure-Baseline/Terraform/04-Network-Hub seems to require a `location` in put that is not given so terraform prompts for input in the github action.

https://learn.hashicorp.com/tutorials/terraform/automate-terraform#automated-terraform-cli-workflow

I was following this file for reference https://github.com/Azure/AKS-Landing-Zone-Accelerator/blob/main/Scenarios/Secure-Baseline/Terraform/workflows/README.md#create-storage-account-for-terraform-state-files

**Comment by defenestration** [comment]
some other terraform variables missing from that deployInfrastructure.yaml
 
    TF_VAR_prefix
    TF_VAR_container_name

**Comment by mosabami** [comment]
@defenestration  apologies for the late response to this. I believe this issue has been fixed now with #19 . let me know if you still run into issues.
