### ISSUE TITLE
Ensure that following deployment steps for build intelligent apps works without any error

### ISSUE THREAD

**Issue by mosabami** [Azure/AKS-Landing-Zone-Accelerator#73]
The Readme file for the Build intelligent apps scenario provides instructions on how to deploy the scenario at a high level. Some steps might be missing. Follow the instructions and make updates to the deployment instructions as you go. Also provide more details about which environment variables need to be updated in the config map and provide screenshots of the app working. Make changes to the bicep and k8s files as well as required. Create a new branch out of the opernai-embeddings branch: https://github.com/Azure/AKS-Landing-Zone-Accelerator/tree/openai-embeddings/Scenarios/AKS-OpenAI-CogServe-Redis-Embeddings

Acceptance criteria:
1) Instructions and other files within the "AKS-OpenAI-CogServe-Redis-Embeddings" folder updated so that a user can successfully deploy the scenario
2) PR submitted to the opernai-embeddings branch

**Comment by khowling** [comment]
#79

**Comment by khowling** [comment]
#79

**Comment by mosabami** [comment]
completed by @lenisha
