### ISSUE TITLE
Update one of the Microservices in the AKS openai demo to use Java (spring boot) as a programing language

### ISSUE THREAD

**Issue by mosabami** [Azure/AKS-Landing-Zone-Accelerator#76]
The AKS product team recently released the openai demo you can find here: https://github.com/Azure-Samples/aks-store-demo/tree/main. It uses Javacript, Go, Rust, Python and Vue, but not Java, one of the most important programming languages our customers use. Pick one of the microservices written in Rust (because multiple microservices are written in rust) and convert it to Java. Preferable convert this microservice: https://github.com/Azure-Samples/aks-store-demo/tree/main/src/product-service

Acceptance criteria:
A rust microservice is converted to Java spring
PR submitted to the main branch of the application

**Comment by aymenfurter** [comment]
Hi @mosabami - Should I start work on this item? Can you assign it to me?

**Comment by aymenfurter** [comment]
PR open: https://github.com/Azure-Samples/aks-store-demo/pull/56

**Comment by mosabami** [comment]
unfortunately the team doesnt have the resources to keep this java version maintained
