### ISSUE TITLE
[BUG] Scenarios/AKS-OpenAI-CogServe-Redis-Embeddings : OpenAIName 

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Landing-Zone-Accelerator#79]
**Describe the bug**
The bicep deployment fails with error, because `parameters.json` file has invalid value

```
"OpenAIName" : {
        "value": "<name for your OpenAI service>"
      },
```

Need to add instructions in README for user to set there own unique value in this parameter.  **NOTE: Globally unique value required***

#73

**Comment by mosabami** [comment]
fixed with #71
