### ISSUE TITLE
[BUG] Scenarios/AKS-OpenAI-CogServe-Redis-Embeddings : OpenAI needs to be registered

### ISSUE THREAD

**Issue by khowling** [Azure/AKS-Landing-Zone-Accelerator#80]
Need to Add to the README: 

Azure OpenAI requires registration and is currently only available to approved enterprise customers and partners. Customers who wish to use Azure OpenAI are required to submit [a registration form](https://aka.ms/oai/access).

#73

**Comment by mosabami** [comment]
fixed with #71
